# Generated by Django 5.2.2 on 2025-06-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoloclassifier',
            name='categories',
            field=models.TextField(null=True),
        ),
    ]
